---
- block:
    - name: Show Active Status
      bigip_command:
        provider: "{{ provider }}"
        commands: show /cm failover-status
      register: failover

    - name: Active Status Assertion
      assert:
        that:
          - "'ACTIVE' in failover.stdout_lines[0][4]"

    - name: Import SSL Private Key with passphrase
      bigip_ssl_key:
        provider: "{{ provider }}"
        name: "{{ service_name }}-{{ year }}"
        content: "{{ lookup('file', './files/site_certificate.key') }}"
        passphrase: "{{ passphrase }}"
        partition: "{{ partition }}"
      when: passphrase | length > 0

    - name: Import SSL Private Key without passphrase
      bigip_ssl_key:
        provider: "{{ provider }}"
        name: "{{ service_name }}-{{ year }}"
        content: "{{ lookup('file', './files/site_certificate.key') }}"
        partition: "{{ partition }}"
      when: passphrase | length == 0

    - name: Import SSL Certificate
      bigip_ssl_certificate:
        provider: "{{ provider }}"
        name: "{{ service_name }}-{{ year }}"
        content: "{{ lookup('file', './files/site_certificate.crt') }}"
        partition: "{{ partition }}"

    - name: Save Configuration and Sync to Standby
      bigip_configsync_action:
        provider: "{{ provider }}"
        device_group: "{{ sync_group }}"
        sync_device_to_group: yes
  
  delegate_to: localhost